name: Verificação Básica do Código Python

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  verificar-codigo:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código
        uses: actions/checkout@v4

      - name: Configurar Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Instalar dependências e linter
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Verificar código com flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics
